import { StyleSheet } from "react-native";

const css = StyleSheet.create({
    pagina: { flex: 1, backgroundColor: "#f5f7fb" },
    topo: { backgroundColor: "#2f6bff", flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14 },
    usuario: { flexDirection: "row", alignItems: "center" },
    avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#6e96ff", alignItems: "center", justifyContent: "center", marginRight: 10 },
    avatarTexto: { color: "#ffffff", fontWeight: "800" },
    saudacao: { color: "#cddaff", fontSize: 12 },
    nomeUsuario: { color: "#ffffff", fontSize: 16, fontWeight: "700" },
    botaoSair: { borderWidth: 1, borderColor: "#7da1ff", borderRadius: 12, paddingHorizontal: 12, paddingVertical: 7 },
    textoSair: { color: "#ffffff", fontWeight: "700", fontSize: 12 },
    resumoAzul: { backgroundColor: "#2f6bff", paddingHorizontal: 20, paddingBottom: 20 },
    rotuloSaldo: { color: "#b9ccff", fontSize: 12, marginTop: 8 },
    saldo: { color: "#ffffff", fontSize: 31, fontWeight: "800", marginTop: 5, marginBottom: 22 },
    cartaoResumo: { backgroundColor: "#ffffff", borderRadius: 22, flexDirection: "row", paddingVertical: 17, paddingHorizontal: 15 },
    resumoItem: { flex: 1, flexDirection: "row", alignItems: "center" },
    divisor: { width: 1, backgroundColor: "#edf0f5", marginHorizontal: 12 },
    iconeCirculo: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", marginRight: 9 },
    fundoVerde: { backgroundColor: "#e9faf3" },
    fundoVermelho: { backgroundColor: "#fff0ee" },
    fundoCinza: { backgroundColor: "#eef1f6" },
    verde: { color: "#46c79a", fontWeight: "800" },
    vermelho: { color: "#ff8274", fontWeight: "800" },
    cinza: { color: "#98a5b8", fontWeight: "800" },
    rotuloResumo: { color: "#9aa5b4", fontSize: 10 },
    valorResumo: { color: "#25344c", fontSize: 13, fontWeight: "800", marginTop: 2 },
    conteudo: { padding: 20 },
    linhaTitulo: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
    tituloSecao: { color: "#27364e", fontSize: 16, fontWeight: "800" },
    periodo: { color: "#a3adba", fontSize: 10 },
    acessos: { flexDirection: "row", justifyContent: "space-between", marginBottom: 28 },
    acesso: { width: "30%", backgroundColor: "#ffffff", borderRadius: 15, alignItems: "center", paddingVertical: 15, shadowColor: "#2d3e58", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.08, shadowRadius: 7, elevation: 2 },
    iconeAcesso: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", marginBottom: 9 },
    textoAcesso: { color: "#354258", fontSize: 11, fontWeight: "700" },
    tituloLancamentos: { color: "#27364e", fontSize: 16, fontWeight: "800", marginBottom: 12 },
    semLancamentos: { backgroundColor: "#ffffff", borderRadius: 16, padding: 22, alignItems: "center" },
    semLancamentosTitulo: { color: "#435069", fontWeight: "700", marginBottom: 7, textAlign: "center" },
    semLancamentosTexto: { color: "#9aa5b4", fontSize: 12, lineHeight: 18, textAlign: "center" },
    menuInferior: { height: 72, backgroundColor: "#ffffff", borderTopWidth: 1, borderTopColor: "#edf0f5", flexDirection: "row", alignItems: "center", justifyContent: "space-around", paddingHorizontal: 4 },
    itemMenu: { width: 66, alignItems: "center" },
    menuAtivo: { color: "#2f6bff", fontSize: 22 },
    menuIcone: { color: "#aab4c3", fontSize: 18 },
    menuTextoAtivo: { color: "#2f6bff", fontSize: 9, marginTop: 3 },
    menuTexto: { color: "#aab4c3", fontSize: 9, marginTop: 5 },
    botaoMais: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#2f6bff", alignItems: "center", justifyContent: "center", marginTop: -32, borderWidth: 4, borderColor: "#ffffff", elevation: 5 },
    mais: { color: "#ffffff", fontSize: 29, lineHeight: 31 },
});

export default css;
