import { StyleSheet } from "react-native";

export default StyleSheet.create({
    pagina: { flex: 1, backgroundColor: "#f6f7fc" },
    topo: { backgroundColor: "#fff", padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    titulo: { fontSize: 22, fontWeight: "800", color: "#142849" },
    subtitulo: { fontSize: 12, color: "#8c9bb5", marginTop: 5 },
    logo: { width: 42, height: 48 },
    busca: { marginHorizontal: 16, marginTop: 20, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", backgroundColor: "#fff", borderWidth: 1, borderColor: "#e3e8f2", borderRadius: 15 },
    lupa: { fontSize: 24, color: "#8c9bb5", marginRight: 10 },
    inputBusca: { flex: 1, minHeight: 46, color: "#142849", fontSize: 14 },
    limpar: { minHeight: 44, minWidth: 32, alignItems: "center", justifyContent: "center" },
    lista: { padding: 16, paddingTop: 20, paddingBottom: 30 },
    resumo: { flexDirection: "row", marginBottom: 20 },
    contador: { flex: 1, padding: 16, borderRadius: 20, borderWidth: 1, gap: 8 },
    enviado: { backgroundColor: "#f0fbf6", borderColor: "#c4efdd" },
    numero: { color: "#142849", fontSize: 26, fontWeight: "800" },
    legenda: { color: "#7084a3", fontSize: 12 },
    icone: { width: 38, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#fff5db" },
    iconeEnviado: { backgroundColor: "#e4f8ef" },
    simbolo: { fontSize: 23, color: "#b58100" },
    verde: { color: "#00bd78" },
    cartao: { backgroundColor: "#fff", padding: 16, borderRadius: 22, borderWidth: 1, borderColor: "#e3e8f2", marginBottom: 12, shadowColor: "#142849", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },
    linha: { flexDirection: "row", gap: 12, alignItems: "flex-start" },
    descricao: { flex: 1 },
    nome: { color: "#142849", fontWeight: "700", fontSize: 14, lineHeight: 20 },
    valor: { color: "#142849", fontSize: 13, fontWeight: "800", maxWidth: "38%" },
    detalhe: { color: "#8c9bb5", fontSize: 11, marginTop: 5 },
    textoBotao: { color: "#326bff", fontSize: 12, fontWeight: "700" },
    botaoAnexar: { marginTop: 14, minHeight: 44, padding: 12, borderRadius: 15, borderWidth: 1, borderColor: "#326bff", backgroundColor: "#f6f8ff", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
    desabilitado: { opacity: 0.5 },
    arquivo: { backgroundColor: "#f6f7fc", borderRadius: 12, padding: 12, marginTop: 14, flexDirection: "row", alignItems: "center", gap: 8 },
    nomeArquivo: { flex: 1, color: "#637697", fontSize: 11 },
    status: { color: "#00bd78", fontSize: 11, fontWeight: "700" },
    aviso: { padding: 20, alignItems: "center", gap: 10 },
    textoAviso: { color: "#637697", textAlign: "center", lineHeight: 21 },
    erro: { color: "#b53a36", textAlign: "center", lineHeight: 21 },
});
