import { StyleSheet } from "react-native";

export default StyleSheet.create({
    pagina: { flex: 1, backgroundColor: "#f6f7fc" },
    topo: { backgroundColor: "#ffffff", padding: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    titulo: { fontSize: 22, fontWeight: "800", color: "#142849" },
    subtitulo: { fontSize: 12, color: "#8c9bb5", marginTop: 5 },
    logo: { width: 42, height: 48 },
    controles: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 14 },
    busca: { backgroundColor: "#ffffff", borderRadius: 15, borderWidth: 1, borderColor: "#e3e8f2", paddingHorizontal: 14, flexDirection: "row", alignItems: "center" },
    lupa: { color: "#899bb7", fontSize: 24, marginRight: 10 },
    inputBusca: { flex: 1, minHeight: 46, fontSize: 14, color: "#142849" },
    filtros: { flexDirection: "row", gap: 8, alignItems: "center", marginTop: 15 },
    filtro: { paddingHorizontal: 16, minHeight: 36, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: "#ffffff", borderWidth: 1, borderColor: "#e3e8f2" },
    filtroAtivo: { backgroundColor: "#326bff", borderColor: "#326bff" },
    textoFiltro: { color: "#637697", fontSize: 12, fontWeight: "700" },
    textoAtivo: { color: "#ffffff" },
    ordenar: { marginLeft: "auto", paddingHorizontal: 10 },
    lista: { paddingHorizontal: 20, paddingBottom: 28 },
    linha: { flexDirection: "row", alignItems: "center", backgroundColor: "#ffffff", padding: 15, minHeight: 82, borderBottomWidth: 1, borderColor: "#e6eaf3", gap: 10 },
    primeiraLinha: { borderTopLeftRadius: 20, borderTopRightRadius: 20, borderTopWidth: 1 },
    ultimaLinha: { borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
    icone: { width: 36, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" },
    fundoReceita: { backgroundColor: "#e6f9f1" },
    fundoDespesa: { backgroundColor: "#ffefeb" },
    seta: { fontSize: 22 },
    receita: { color: "#00bd78" },
    despesa: { color: "#ff745e" },
    descricao: { flex: 1 },
    nome: { color: "#142849", fontSize: 12, fontWeight: "700", lineHeight: 17 },
    detalhe: { color: "#8c9bb5", fontSize: 10, marginTop: 4 },
    valores: { maxWidth: "38%", alignItems: "flex-end" },
    valor: { color: "#142849", fontWeight: "800", fontSize: 12 },
    aviso: { padding: 25, alignItems: "center", gap: 12 },
    textoAviso: { color: "#637697", textAlign: "center", lineHeight: 21 },
    erro: { color: "#b53a36", textAlign: "center", lineHeight: 21 },
    link: { color: "#326bff", fontWeight: "700", padding: 10 },
    formulario: { padding: 20, paddingBottom: 40 },
    rotulo: { color: "#536278", fontSize: 13, fontWeight: "600", marginTop: 8, marginBottom: 8 },
    opcoes: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
    opcao: { borderRadius: 12, borderWidth: 1, borderColor: "#dbe4f3", backgroundColor: "#ffffff", paddingHorizontal: 13, paddingVertical: 12 },
    voltar: { color: "#326bff", fontWeight: "700", paddingVertical: 10 },
});
