import { StyleSheet } from "react-native";

export default StyleSheet.create({
    pagina: { flex: 1, backgroundColor: "#ffffff" },
    topo: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, minHeight: 60, borderBottomWidth: 1, borderColor: "#edf0f7" },
    voltar: { width: 42, height: 44, justifyContent: "center", alignItems: "center" },
    setaVoltar: { color: "#142849", fontSize: 24 },
    titulo: { color: "#142849", fontSize: 16, fontWeight: "700" },
    teclado: { flex: 1 },
    formulario: { padding: 18, flexGrow: 1 },
    campos: { flexGrow: 1, flexShrink: 0 },
    abas: { flexDirection: "row", backgroundColor: "#f6f7fc", padding: 5, borderRadius: 19, marginBottom: 22 },
    aba: { flex: 1, minHeight: 40, borderRadius: 14, justifyContent: "center", alignItems: "center" },
    abaAtiva: { backgroundColor: "#ffffff", elevation: 2, shadowColor: "#18335b", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.07, shadowRadius: 5 },
    textoAba: { color: "#8b9bb6", fontSize: 13, fontWeight: "700" },
    verde: { color: "#00bc7d" },
    vermelho: { color: "#ff715b" },
    valorCard: { padding: 16, borderRadius: 20, marginBottom: 22 },
    fundoReceita: { backgroundColor: "#e6f8f0" },
    fundoDespesa: { backgroundColor: "#ffede8" },
    rotulo: { color: "#607695", fontSize: 11, fontWeight: "600", marginBottom: 6 },
    linhaValor: { flexDirection: "row", alignItems: "center", gap: 8 },
    cifra: { fontSize: 17, fontWeight: "700" },
    valor: { flex: 1, fontSize: 30, fontWeight: "800", minHeight: 42, paddingVertical: 0 },
    linha: { flexDirection: "row", gap: 12 },
    metade: { flex: 1 },
    rodape: { marginTop: "auto", paddingTop: 12, paddingBottom: 2 },
    salvar: { minHeight: 46, borderRadius: 18, backgroundColor: "#326bff", alignItems: "center", justifyContent: "center", shadowColor: "#326bff", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.18, shadowRadius: 8, elevation: 3 },
    textoSalvar: { color: "#ffffff", fontWeight: "700", fontSize: 13 },
    desabilitado: { opacity: 0.6 },
    maisOpcoes: { color: "#637697", fontSize: 12, paddingVertical: 8 },
    aviso: { padding: 20, gap: 15, alignItems: "center" },
    erro: { color: "#b53a36", lineHeight: 20, marginBottom: 12 },
    secao: { fontSize: 15, fontWeight: "700", color: "#142849", marginTop: 8, marginBottom: 16 },
    ajuda: { color: "#637697", fontSize: 12, lineHeight: 18, marginBottom: 12 },
    anexo: { padding: 18, borderWidth: 1, borderStyle: "dashed", borderColor: "#dbe4f3", borderRadius: 14, alignItems: "center", marginBottom: 20, gap: 6 },
    nomeAnexo: { color: "#142849", fontSize: 13, textAlign: "center" },
    link: { color: "#326bff", fontSize: 13, fontWeight: "600", padding: 8 },
    criarCategoria: { alignSelf: "flex-start", borderWidth: 1, borderColor: "#dbe4f3", borderRadius: 10, marginBottom: 12 },
    recorrencia: { backgroundColor: "#f6f7fc", borderRadius: 16, padding: 14, marginBottom: 20 },
});
